// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_supporter = "CgkI8dy52uQXEAIQAQ"; // <GPGSID>
        public const string achievement_sports_fanatic = "CgkI8dy52uQXEAIQAw"; // <GPGSID>
        public const string achievement_ballistic_blunder = "CgkI8dy52uQXEAIQBw"; // <GPGSID>
        public const string achievement_precision_dropper = "CgkI8dy52uQXEAIQBg"; // <GPGSID>
        public const string achievement_ball_collector = "CgkI8dy52uQXEAIQAg"; // <GPGSID>
        public const string achievement_cascade_champion = "CgkI8dy52uQXEAIQBQ"; // <GPGSID>
        public const string achievement_football_frenzy = "CgkI8dy52uQXEAIQBA"; // <GPGSID>
        public const string leaderboard_high_score = "CgkI8dy52uQXEAIQCA"; // <GPGSID>

}

